version: "3.1"
services:
  frontend: 
    image: volunux/hng9i-fe
    restart: always
    networks:
      - hng9_2
    ports:
      - 3000:3000
    
  api:
    image: volunux/hng9i-be
    restart: always
    networks:
      - hng9_2
    ports:
      - 8000:8000

networks:
  hng9_2:
