version: "3.1"
services:
  frontend: 
    build: ./frontend
    restart: always
    networks:
      - hng9_2
    ports:
      - 3000:3000
    
  api:
    build: ./api
    restart: always
    networks:
      - hng9_2
    ports:
      - 8000:8000

networks:
  hng9_2:
